### ISSUE TITLE
Error in SPARQL update

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#115]
When I do:
```
exe/load call Sparql -i organizations.sparql
```
I see getting lots of errors like this:
```
ERROR Error in SPARQL update. wrong number of arguments (given 1, expected 0)
```

**Comment by jcoyne** [comment]
When I remove the `rescue` block I get this trace:
```
	 9: from /Users/jcoyne/workspace/dlss-labs/rialto-etl/lib/rialto/etl/writers/sparql_writer.rb:62:in `block in put'
	 8: from /Users/jcoyne/workspace/dlss-labs/rialto-etl/lib/rialto/etl/writers/sparql_writer.rb:100:in `send_batch'
	 7: from /Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.12.2/lib/faraday/connection.rb:186:in `post'
	 6: from /Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
	 5: from /Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
	 4: from /Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
	 3: from /Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	 2: from /Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http_persistent.rb:22:in `net_http_connection'
	 1: from /Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http_persistent.rb:22:in `new'
/Users/jcoyne/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/net-http-persistent-3.0.0/lib/net/http/persistent.rb:505:in `initialize': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

**Comment by jcoyne** [comment]
this was fixed in a newer version of Faraday: https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter/net_http_persistent.rb#L11
But we can’t upgrade Faraday, because oauth2 depends on Faraday 0.12.0
