### ISSUE TITLE
NoMethodError for 'join' when loading grants

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss-labs/rialto-etl#245]
```
         5: from /opt/app/vitro/.rvm/gems/ruby-2.5.1@rialto/gems/parallel-1.12.1/lib/parallel.rb:486:in `call_with_index'
         4: from /opt/app/vitro/rialto/rialto-etl/lib/rialto/etl/cli/composite_etl.rb:51:in `block (2 levels) in load'
         3: from /opt/app/vitro/rialto/rialto-etl/lib/rialto/etl/cli/composite_etl.rb:64:in `handle_row'
         2: from /opt/app/vitro/rialto/rialto-etl/lib/rialto/etl/cli/composite_etl.rb:91:in `extract'
         1: from /opt/app/vitro/rialto/rialto-etl/lib/rialto/etl/cli/composite_etl.rb:91:in `open'
/opt/app/vitro/rialto/rialto-etl/lib/rialto/etl/cli/composite_etl.rb:92:in `block in extract': undefined method `join' for #<IO:<STDOUT>> (NoMethodError)
```

**Comment by jcoyne** [comment]
I believe this is caused by the error case returning a stream rather than an enumerable.  Above there were messages such as:

```
aborting meadds, failed with RuntimeError: There was a problem with the request
to `/mais/sera/v1/api?scope=sera.stanford-only&sunetId=meadds` (404): null
aborting , failed with RuntimeError: There was a problem with the request to `/m
ais/sera/v1/api?scope=sera.stanford-only&sunetId=` (404): null
aborting mja14, failed with RuntimeError: There was a problem with the request t
o `/mais/sera/v1/api?scope=sera.stanford-only&sunetId=mja14` (500): null
```
